### PR TITLE
fix(backend): allow a custom API root for backend

### LINKED ISSUE #7168: Backend for self-hosted Gitlab still queries gitlab.com
**Describe the bug**
I configured a backend for my hosted version of Gitlab
```yaml
  name: gitlab
  repo: web/landing
  auth_type: pkce # Required for pkce
  app_id: *******
  api_root: https://gitlab.****/api/v4
  base_url: https://gitlab.*****
  auth_endpoint: oauth/authorize
```
On login:
- I get rediricted to my hosted app :heavy_check_mark: 
- a call is made to `GET https://gitlab.*****/api/v4/projects/web%2Flanding` :heavy_check_mark: 
- then a call to `GET https://gitlab.com/api/v4/projects/web%2Flanding` :x: 

Of course the 3rd call gives a 404 and login workflow stops.

I looked at the sources but couldn't find a static ref to `gitlab.com`.

**To Reproduce**
1. Configure a backend for a hosted gitlab
2. Try to login

**Expected behavior**
No call should be made to `gitlab.com`

**Screenshots**
Screenshot from 2024-04-09 17-50-08

**Applicable Versions:**
 - Decap CMS version: 3.0.0 (https://unpkg.com/decap-cms@^3.0.0/dist/decap-cms.js)
 - Git provider:Gitlab
 - OS: Fedora 39
 - Browser version: Firefox 129.0.4

**CMS configuration**
```yaml
collections:
  - name: 'posts'
    label: "Posts de blog"
    folder: "blog/posts"
    create: true
    fields:
      - { label: "Layout", name: "layout", widget: "hidden", default: "post"}
      - { label: "Titre", name: "title", widget: "string"}
      - { label: "Image", name: "image", widget: "image"}
      - { label: "Miniature", name: "thumbnail", widget: "image"}
      - { label: "Categorie", name: "categoriy", widget: "string"}
      - { label: "Résumé", name: "excerpt", widget: "markdown"}
      - { label: "Contenu", name: "body", widget: "markdown"}

locale: fr

media_folder: "assets/posts"
backend:
  name: gitlab
  repo: web/landing
  auth_type: pkce # Required for pkce
  app_id: *******
  api_root: https://gitlab.****/api/v4
  base_url: https://gitlab.*****
  auth_endpoint: oauth/authorize
```

### PR DESCRIPTION
**Pull request by JbIPS**
In case of a self-hosted Gitlab, the API request to get the default branch always call gitlab.com.
This commit allow to pass a custom API root from the config to the API call.

Fixes #7168

- [x] I have read the [contribution guidelines](https://github.com/decaporg/decap-cms/blob/main/CONTRIBUTING.md).

### CODE REVIEW

**Comment by martinjagodic** [comment]
@JbIPS could you add this new setting to docs also? the best way is to submit a PR here: https://github.com/decaporg/decap-website

**Comment by JbIPS** [comment]
Actually, the `apiRoot` setting is not new (https://decapcms.org/docs/backends-overview/), it was just not used for the calls on GitLab branches.

**Review by martinjagodic — APPROVED** [review]

**Comment by dbtek** [comment]
Hi @JbIPS. Thanks for the effort.
I'd like to use decap with self hosted Gitlab and blocked by this issue also. Can we see the fix in a release any time soon?

**Comment by JbIPS** [comment]
Hi @dbtek! Did you add `branch: master` in your config? It is a valid workaround for now

**Comment by dbtek** [comment]
Hi @JbIPS. Yeah I found it by accident 😊. It seems working now. Thanks!

**Pull request merged**
