### PR TITLE
Update emotion to v11

### PR DESCRIPTION
**Pull request by vbrzezina**
**Summary**

Update emotion to v11 for compatibility with MUI5

**Test plan**

_One test site is currently broken and I'm having trouble figuring out why any help appricited_

**Checklist**
- [x] I have read the [contribution guidelines](../CONTRIBUTING.md).
- [x] Code is formatted via running `yarn format`.
- [ ] Tests are passing via running `yarn test`.
- [ ] The status checks are successful (continuous integration). Those can be seen below.

### CODE REVIEW

**Comment by martinjagodic** [comment]
@vbrzezina can you please solve the conflicts? We would be happy to merge this!

**Comment by martinjagodic** [comment]
@vbrzezina could you solve this? Otherwise, we will pick this up in a new PR.

**Comment by demshy** [comment]
Hope you don't mind me updating this, our goal is to get to react 18 and emotion is one of the libraries on top of the priority list before that happens.

**Comment by demshy** [comment]
closing in favour of https://github.com/decaporg/decap-cms/pull/6940 (where we did this a bit cleaner)

**Pull request closed without merging**
