### PR TITLE
feat(backend): add gitea backend

### LINKED ISSUE #1109: Support for Gitea
Currently, Netlify CMS works only with GitHub, while for many companies this might be not the best option. It would be great if Netlify CMS can also support Gitea (https://github.com/go-gitea/gitea)

### PR DESCRIPTION
**Pull request by denyskon**
**Summary**

Introduces Gitea as new backend for Decap CMS. Fixes #1109 

**Checklist**

- [x] added backend
- [x] added unit tests
- [x] added docs
- [x] tested creating/updating/deleting entries, upload/delete media 

**A picture of a cute animal (not mandatory but encouraged)**

### CODE REVIEW

**Comment by denyskon** [comment]
@martinjagodic I think this PR is ready. Would be nice though if somebody else would test it before merging. You can use the config in dev-test, the client ID is registered on https://try.gitea.io for http://localhost:8080/backends/gitea/ as redirect URL.

**Comment by denyskon** [comment]
@martinjagodic I resolved the conflicts and changed the naming to match the recent changes. One question, as this is my first time working with such a monorepo: do I have to bump the version number for the `decap-cms-lib-auth` package as I changed it too?
Besides from that, this PR should be ready again.

**Comment by martinjagodic** [comment]
Thanks, @denyskon. Versions are bumped automatically when we create a release, so you don't need to do that.

**Comment by martinjagodic** [comment]
Hi @denyskon I know it's been a while... Are you willing to dive into why tests are failing?

**Comment by denyskon** [comment]
@martinjagodic Sorry, I didn't notice the lint failure, and build failed because of a dependency update on master. It should all pass now :)

**Review by demshy — APPROVED** [review]
Great! We could add some e2e tests, but since they are probably awaiting a huge overhaul I think we can add that later.

**Pull request merged**
