### PR TITLE
wip: Implementing New UI

### PR DESCRIPTION
**Pull request by Daniel-Mendes**
**Summary**

This pull request is a continuation of the UX improvements initiated in #2557. It merges the work done in the [v3-ui-redesign](https://github.com/decaporg/decap-cms/tree/v3-ui-redesign) branch with the current master branch, introducing a new layout, dark mode, and a mobile-responsive design.

## Preview
- Storybook (UI Components): https://decap-next-ui-storybook.netlify.app
- Demo (Dashboard Preview): https://decap-next-ui-demo.netlify.app

## Features

- **New Layout**: A modernized interface that improves user experience.
- **Dark Mode**: A dark theme for better user comfort.
- **Responsive Design**: Optimized for mobile devices, ensuring a seamless experience across different screen sizes.

## Areas for Improvement

The following features are not implemented yet but are recommended for future updates:

- **Accessibility Enhancements**: Improve overall accessibility to meet WCAG standards.
- **RTL (Right-to-Left) Support**: Add support for right-to-left languages.

> Note: These improvements could be facilitated by migrating components to [Radix UI](https://www.radix-ui.com/) or [React Aria](https://react-spectrum.adobe.com/react-aria/index.html)

## Out of scope

The following features are not included in this pull request and will be considered in future updates:

- Theming Accent Color
- Online editing of `config.yml`
- Dashboard Page
- Unsplash and Pexels Media Library Addons

## Roadmap

<details>
<summary>
<h3>Phase 1: Components and stories migration</h3>
  
 In this phase, the goal is to migrate all components and stories to the new UI design.
</summary>

##### Pages
- [ ] MediaLibrary
- [ ] Authentication Page
  - [ ] Login Button

##### Components
- [x] App Bar
- [x] App Wrap
- [x] Avatar
- [x] Backdrop
- [x] Buttons  #3257
  - [x] Avatar Button
  - [x] Button
  - [x] Button Group
  - [x] Icon Button
- [x] Card
- [x] Dialog
- [x] Editor
- [x] Field
- [x] Fullscreen
- [x] Icon
- [x] Label
- [x] Logo
- [x] Logo Tile
- [x] Menu
- [ ] MediaDialog
- [x] Modal
- [x] NavMenu
- [x] Popover
- [x] Portal
- [ ] Responsive Layout
- [x] Search Bar
- [x] Table
- [x] Tag
- [x] Thumbnail
- [x] Toast
- [x] Toggle Switch
- [x] Tooltip
- [x] Transitions
- [x] Tree
- [x] UIContext
- [x] UserMenu

##### Inputs
- [x] Boolean Input 
- [x] Date Input
- [ ] List Input
- [x] Markdown Input
- [x] Object Input
- [x] Select Input
- [x] Text Input

</details>

<details>
<summary>
<h3>Phase 2: App Core Migration</h3>
  
 The focus of this phase is to gradually migrate the decap-cms-core code to utilize the new UI components.
</summary>

#### Progress Overview
- [ ] Migrate components from Netlify Theme to Decap Theme

- [ ] Base Layout
  - [x] Nav
  - [ ] Header
    - [ ] Page Title
    - [ ] Breadcrumb
    - [x] Search Bar
    - [x] User Menu
- [ ] Authentication Pages
  - [ ] Backend Aws Cognito Github Proxy
  - [ ] Backend Azure
  - [ ] Backend Git Gateway
  - [ ] Backend Gitea
  - [ ] Backend Github
  - [ ] Backend Gitlab
  - [ ] Backend Proxy
  - [x] Backend Test
- [x] List Collection Page
- [ ] Edit Collection Page
  - [ ] Widgets
    - [x] Widget Boolean
    - [ ] Widget Code
    - [ ] Widget Colorstring
    - [x] Widget Datetime
    - [ ] Widget File
    - [ ] Widget Image
    - [ ] Widget List
    - [x] Widget Map
    - [x] Widget Markdown
    - [x] Widget Number
    - [ ] Widget Object
    - [ ] Widget Relation
    - [x] Widget Select
    - [x] Widget String
    - [x] Widget Text
- [x] Editorial Workflow Page

</details>

### Breaking Changes

- **Deprecating** `display_url`: Replaced by the new `resources` namespace. (see below)
- **Deprecating** `logo_url`: Replaced by the new `branding` namespace. (see below)

### New Additions

-  **`icon` Property**: Allows customization of icons for collections:

```yml
collections: 
  - name: 'posts'
    label: 'Posts'
    icon: 'edit-3' # Icon value from packages/decap-cms-ui-next/src/Icon/icons
  ```

- **`resources` Namespace**: Enables external links to resources like the main site, git repo, analytics, and deploy services.
```yml
resources: 
  - name: 'netlify'
    label: 'Netlify'
    url: 'https://app.netlify.com/sites/decap-cms/overview'
    icon: "server" # Icon value from packages/decap-cms-ui-next/src/Icon/icons
  ```
  
- **`branding` Namespace**: Customize the logo, title and potentially the theme in future updates.
```yml
branding:
  logo_url: 'https://admin.gov/logo.png'
  app_name: 'Admin Panel'
  theme:
    primary: '#112f4e'
    draft: '#2563eb'
    in_review: '#eab308'
    ready: '#047857'
    # Additional theme properties to be defined
```

- **`analytics` Namespace**: Configures dashboard analytics provider.
```yml
analytics:
  name: 'plausible'
  config:
    site_id: 'decapcms.org'
    api_key: 'as3f3rsd6734232g32'
    api_endpoint: 'https://analytics.decapcms.org/api' # Optional for self-hosted services
    is_public: true # Optional (default: false) for public analytics; no `api_key` needed
```

## New Customisation Functions

To further extend the customization capabilities of Decap CMS, new functions have been introduced:

- **`registerAnalytics`**: Allows developers to register custom analytics providers.

```js
CMS.registerAnalytics(name, AnalyticsClass)
```

- **`registerIcon`**: Enables the registration of custom icons, making it easier to expand the icon library used throughout the CMS:

```js
CMS.registerIcon(name, icon)
```

- **`registerTheme`**: Facilitates the registration of custom themes, providing a way to extend or override the default theming options

```js
CMS.registerTheme(name, theme)
```

### CODE REVIEW

**Comment by martinjagodic** [comment]
@Daniel-Mendes this is a huge job done, thanks! 🙏 This will take some time to review, so I ask for some patience 😅

We will not merge this to master but create a `next` environment like you proposed. There we can start porting other components and doing work that could go into the next release.

**Comment by Daniel-Mendes** [comment]
In the `next` branch, we should implement a [storybook.decapcms.org](https://storybook.decapcms.org/) (same as [storybook.netlifycms.org](https://storybook.netlifycms.org)) and [next.decapcms.org](https://next.decapcms.org) (same as [demo.decapcms.org](https://demo.decapcms.org)), so everyone can follow the current progress.

**Comment by Daniel-Mendes** [comment]
**What's new:**

- Newest Layout
- Dark Mode Switch
- Quick Add
- Custom icon, position, url for collections (should be renamed to resources maybe)

https://github.com/decaporg/decap-cms/assets/28825568/43509bd2-95bb-4371-afb8-4ed7f372441b

**Comment by Daniel-Mendes** [comment]
I fixed merge conflicts with current decap-cms/next branch.

**Pull request closed without merging**
