### PR TITLE
Add <span> tag to (optional) suffix for customization

### PR DESCRIPTION
**Pull request by leomp12**
With the <span> (or any) tag we can add CSS like:

```css
body {
  [class*=FieldLabel-fieldLabel] span {
    display: none;
  }
}
```

to hide or customize the _(optional)_ suffix.

It'll specially useful when majority of the fields are optional, we can also use CSS :has to select required fields and add a _*_ for example.

**Summary**

**Test plan**

**Checklist**

Please add a `x` inside each checkbox:

- [x] I have read the [contribution guidelines](https://github.com/decaporg/decap-cms/blob/master/CONTRIBUTING.md).

**A picture of a cute animal (not mandatory but encouraged)**

### CODE REVIEW

**Comment by martinjagodic** [comment]
@leomp12 this is a good idea. before we can merge this, please fix the lint error.

**Review by martinjagodic — CHANGES_REQUESTED** [review]
@leomp12 this is a good idea. before we can merge this, please fix the lint error.

**Comment by demshy** [comment]
Hi @leomp12  lint checker is blaming the `packages/decap-cms-core/src/components/Editor/EditorControlPane/EditorControl.js` file
can you please run `npm run format` and see what changes it does?

**Comment by leomp12** [comment]
done @demshy 👍🏾

**Review by martinjagodic — CHANGES_REQUESTED** [review]
@leomp12 an e2e test is failing: Markdown widget code block. I think there's an extra space after `Code Block` in the expected code.

**Comment by demshy** [comment]
@leomp12 to find the cause for the test fail easier you can run cypress in dev mode locally with `npm run test:e2e:dev` and run only the test in question (I think markdown_widget_code_block_spec.js) until it passes

**Review by demshy — APPROVED** [review]

**Review by martinjagodic — APPROVED** [review]

**Pull request merged**
