### PR TITLE
Move if-s to job-level in CI

### PR DESCRIPTION
**Pull request by szepeviktor**
**Summary**

Move if-s to job-level in CI reducing the number of if-s to two.

**Checklist**

Please add a `x` inside each checkbox:

- [ ] I have read the [contribution guidelines](https://github.com/decaporg/decap-cms/blob/master/CONTRIBUTING.md).

**A picture of a cute animal (not mandatory but encouraged)**

image

### CODE REVIEW

**Comment by martinjagodic** [comment]
@szepeviktor can you explain the motivation behind this PR?

**Comment by szepeviktor** [comment]
Yes.
No need for conditions in each step.
Just add one condition to each job.

**Comment by martinjagodic** [comment]
@szepeviktor do you mind fixing the conflict? Sorry it took so long.

**Comment by szepeviktor** [comment]
@martinjagodic Done. No problem.

**Review by martinjagodic — APPROVED** [review]

**Comment by szepeviktor** [comment]
# 🍓

**Pull request merged**
