### PR TITLE
fix: add EOL for files

### LINKED ISSUE #1382: JSON files are saved with no newline at the end of file
**- Do you want to request a *feature* or report a *bug*?**
Bug

**- What is the current behavior?**
Netlify CMS saves JSON data **without** a newline at the end of the file.

**- If the current behavior is a bug, please provide the steps to reproduce.**
Configure a collection type with `format: "json"` and `extension: "json"`, then create and publish a new post in the Dashboard.

**- What is the expected behavior?**
JSON file should created **with** newline at the end of the file.

### PR DESCRIPTION
**Pull request by razonyang**
Closes #1382

**Summary**

**Test plan**

**Checklist**

Please add a `x` inside each checkbox:

- [x] I have read the [contribution guidelines](../CONTRIBUTING.md).

**A picture of a cute animal (not mandatory but encouraged)**

### CODE REVIEW

**Comment by razonyang** [comment]
Hi @martinjagodic, I'm willing to correct it, but I lost my direction after digging into the code, could you please share some hint?

**Comment by demshy** [comment]
hi @razonyang I hope you don't mind me taking this over, but currently recording fixtures does not really work because the whole cypress part is awaiting a large overhaul. The process that I currently use is quite manual and specific, so I will describe it here for future reference (also for me and @martinjagodic). I wanted to write these instructions but after I was finished the tests were working already, so it didn't make sense to me to make you do them again :)

a) run `yarn test:e2e` and wait for it to finish, to see which tests failed
b) run `yarn test:e2e:dev` and manually run the failed test(s) with the console open
c) notice the yellow warning about 404 request right before the test failing - it contains a content hash that you'll want to copy
d) find the correct file for the test in cypress/fixtures and find the request - in this case you could search by the hash start, since only the ending of the content is different
e) once you found the request, find and replace content hash with the one you copied from step c)
repeat b) until the test passes.. by using find and replace you possibly fixed multiple tests so if you suspect this, do a) again

**Comment by razonyang** [comment]
@demshy Of course I don't mind, I'm completely newbie on this project, I have no idea on how to fix the tests, now I learned it from your code.

**Comment by demshy** [comment]
No worries, it's quite overwhelming for most of us. 
As I said the goal is to make this more automatic and documented, but one step at a time I guess :)

Anyhow, this seemed to do the trick

**Review by demshy — APPROVED** [review]

**Pull request merged**
