### PR TITLE
fix: accessibility - color contrast and keyboard navigation

### PR DESCRIPTION
**Pull request by kewitham**
**Summary**

Our team at ada.gov uses Netlify CMS. Recently Terri Youngblood, the accessibility consultant for the DOJ Civil Rights Section, did an audit of Netlify to verify its accessibility and identified some issues. This PR addresses those concerns - specifically color contrast, and keyboard navigation updates.

Screenshot 2023-05-01 at 11 26 45 AM
Screenshot 2023-05-01 at 11 27 00 AM

Screenshot 2023-05-01 at 11 27 22 AM
Screenshot 2023-05-01 at 11 27 33 AM
Screenshot 2023-05-01 at 11 27 39 AM

**Test plan**

1. Verify that the color contrast for the elements now fulfill the contrast ratio requirements:

i.e.
**Before**
image
**After**
image

Note: I used [this tool](https://webaim.org/resources/contrastchecker/) to darken the colors in question until they met the minimum contrast requirements.

2. Verify that you are able to navigate out of the editor panel by using the esc key.
3. Verify that you are able to tab through the media asset modal.

**Checklist**

Please add a `x` inside each checkbox:

- [x] I have read the [contribution guidelines](../CONTRIBUTING.md).

**A picture of a cute animal (not mandatory but encouraged)**
image

### CODE REVIEW

**Comment by martinjagodic** [comment]
Hi @kewitham thanks for this contribution.

This product supports many languages, so aria labels should be translated also. I also don't understand why the Russian translation was modified, perhaps it's just a merge issue?

**Comment by kewitham** [comment]
> Hi @kewitham thanks for this contribution.
> 
> This product supports many languages, so aria labels should be translated also. I also don't understand why the Russian translation was modified, perhaps it's just a merge issue?

@martinjagodic The Russian translation updates are just formatting updates. Do you have an internal resource for translating the aria labels? What are the next steps there?

**Comment by samo4** [comment]
It would be nice if this is split into multiple PRs which encompass logical areas of the changes. I don't have a firm opinion on how to structure this, but first I would recommend moving the formatting of russian translations to separate PR. Also separate PR: aria labels should be split from minor accessibility improvements. That's because currently they need to be translated.

**Comment by kewitham** [comment]
> It would be nice if this is split into multiple PRs which encompass logical areas of the changes. I don't have a firm opinion on how to structure this, but first I would recommend moving the formatting of russian translations to separate PR. Also separate PR: aria labels should be split from minor accessibility improvements. That's because currently they need to be translated.

@samo4 @martinjagodic I have removed the aria label updates and formatting updates from this PR. I will submit another one with just the aria updates

**Comment by kewitham** [comment]
@samo4 @martinjagodic checking back in on this PR - is it good to merge now?

**Review by martinjagodic — APPROVED** [review]

**Comment by martinjagodic** [comment]
@demshy since you're working on updating the markdown editor, is this PR conflicting with your efforts?

**Comment by demshy** [comment]
Some of it for sure, because we had to basically rewrite all keyboard events. I don't mind if this is merged though. 

I will make sure the escape key is handled properly in the new handlers.

**Pull request merged**
