### PR TITLE
feat: changed minimum of 2 locales to minimum of 1

### LINKED ISSUE #6263: Allow i18n to have only one locale
**Is your feature request related to a problem? Please describe.**
If you configure this either globally or on a collection
```yaml
i18n:
  locales: [en]
```
you get this error: `'i18n.locales' must NOT have fewer than 2 items`

If you want to temporarily disable a locale or you are testing only one, this is quite annoying. You would have to change the structure of the i18n object every time, which can be time-consuming if you have a lot of those on file collections for instance.

**Describe the solution you'd like**
Allow i18n.locales to have only one item

**Describe alternatives you've considered**
Currently, you need to set `i18n: false`, which is not technically the same.

### PR DESCRIPTION
**Pull request by dfdez**
**Summary**
I made these PR in order to be able to have only one locale, to cover some use cases in which we want to just have one.

Right now the only workaround is to just set `i18n: false` but this will change how the file / folder structure is generated

closes #6263

**Test plan**

The only modification that I made is to set the `minItems` property of `locales` property from `2` to `1`.

Also I added a test for check that fails when `locales` are less than `1` (Previously there wasn't a test of this)

**Checklist**

Please add a `x` inside each checkbox:

- [x] I have read the [contribution guidelines](../CONTRIBUTING.md).
- [x] Code is formatted via running `yarn format`.
- [x] Tests are passing via running `yarn test`.
- [x] The status checks are successful (continuous integration). Those can be seen below.

**A picture of a cute animal (not mandatory but encouraged)**

image

### CODE REVIEW

**Review by erezrokah — CHANGES_REQUESTED** [review]
Thanks @dfdez, I'm concerned that we might rely of that array to contain more than 1 element if a few places in the codebase.

For example with this change the CMS crashes in the `EditorControlPane.js`
image

Do you mind looking at the error?

**Comment by dfdez** [comment]
> Thanks @dfdez, I'm concerned that we might rely of that array to contain more than 1 element in a few places in the codebase.
> 
> For example with this change the CMS crashes in `EditorControlPane.js` image
> 
> Do you mind looking at the error?

Sure!

**Comment by dfdez** [comment]
The problem was the i18n editor toggle, by having only 1 locale the editor tried to load `locale[1]` creating the [problem](https://github.com/netlify/netlify-cms/pull/6406#pullrequestreview-942044985) showed above.

In [a52ca73](https://github.com/netlify/netlify-cms/pull/6406/commits/a52ca73f2f4acfec2c0acd942cfae02f1c3e66e0) I updated the `EditorInterface.js` to only show the toggle if i18n is enabled and there are multiple locales.

**Comment by dfdez** [comment]
Any news about this? @erezrokah

**Comment by martinjagodic** [comment]
@dfdez any reason why you closed this? This would be great to implement after we solve priority issues.

**Comment by dfdez** [comment]
I thought it was abandoned 🥲 but It can be reopened of course!

**Comment by martinjagodic** [comment]
Not abandoned, just in a long queue :D

**Comment by martinjagodic** [comment]
@dfdez can you solve merge conflicts, please? They appeared because packages and folders were renamed.

**Review by demshy — APPROVED** [review]

**Pull request merged**
